 version: "3.3"

 services:
   app:
     image: node:12-alpine
     command: sh -c "yarn install && yarn dev"
     ports:
       - 1111:3000
     working_dir: /app
     volumes:
       - ./:/app
     restart: always
     expose: ["3000"]
     environment:
       VIRTUAL_PORT: 1111
       VIRTUAL_HOST: "www.soshiharami.com"
       LETSENCRYPT_HOST: "www.soshiharami.com"
       LETSENCRYPT_EMAIL: "soshi@soshiharami.com"
     network_mode: "bridge"
