import Head from "next/head";
import {NextPage} from "next";
import styles from "../styles/Home.module.css";
import {useQuery, gql} from "@apollo/client";
import React from "react";
import {Skills} from "../components/Skills";
import {Contacts} from "../components/Contacts";
import {me} from "../types/Me";

const Home: NextPage = () => {
    const query = gql`
    query {
      me {
        name
        about
        age
        skills {
          id
          name
          types {
            name
            id
          }
        }
        histories {
          id
          time
          title
          about
        }
        contact {
          name
          url
        }
      }
    }
  `;

    const {data, loading, error} = useQuery(query);

    if (loading) {
        return <p>loading...</p>;
    }

    // check for errors
    if (error) {
        return <p>:( an error happened</p>;
    }

    const me: me = data.me[0];

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>hello, I am {me.name}</h1>
                <h1>This is {me.name} portFolio</h1>
                <Skills skills={me.skills} />
                <Contacts contacts={me.contact} />
            </main>

            <footer className={styles.footer}>
                Powered by
                <p className={styles.soshikun}>そうしくん！</p>
            </footer>
        </div>
    );
};

export default Home;
